# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serverApp.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 351)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.messageBox = QtWidgets.QTextEdit(self.centralwidget)
        self.messageBox.setGeometry(QtCore.QRect(9, 181, 671, 71))
        self.messageBox.setObjectName("messageBox")
        self.serverButton = QtWidgets.QPushButton(self.centralwidget)
        self.serverButton.setGeometry(QtCore.QRect(690, 180, 88, 71))
        self.serverButton.setMinimumSize(QtCore.QSize(0, 50))
        self.serverButton.setObjectName("serverButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 260, 671, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openFileButton = QtWidgets.QPushButton(self.layoutWidget)
        self.openFileButton.setObjectName("openFileButton")
        self.horizontalLayout.addWidget(self.openFileButton)
        self.openFileLabel = QtWidgets.QLabel(self.layoutWidget)
        self.openFileLabel.setText("")
        self.openFileLabel.setObjectName("openFileLabel")
        self.horizontalLayout.addWidget(self.openFileLabel)
        self.incomingText = QtWidgets.QTextBrowser(self.centralwidget)
        self.incomingText.setGeometry(QtCore.QRect(10, 10, 671, 161))
        self.incomingText.setObjectName("incomingText")
        self.endButton = QtWidgets.QPushButton(self.centralwidget)
        self.endButton.setGeometry(QtCore.QRect(690, 60, 88, 50))
        self.endButton.setMinimumSize(QtCore.QSize(0, 50))
        self.endButton.setObjectName("endButton")
        self.endButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.endButton_2.setGeometry(QtCore.QRect(690, 10, 88, 50))
        self.endButton_2.setMinimumSize(QtCore.QSize(0, 50))
        self.endButton_2.setObjectName("endButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.serverButton.setText(_translate("MainWindow", "Send"))
        self.openFileButton.setText(_translate("MainWindow", "Open File"))
        self.endButton.setText(_translate("MainWindow", "End\n"
"Connection"))
        self.endButton_2.setText(_translate("MainWindow", "Start\n"
"Connection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
